# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d6ca2fb8c6e7c4081dc6b551194dd6a3f4aa62fe218a550525bc3ac4262a086ec9b4d2b9ccd026df48b61370ad17f8ff8c03be87f0cf5e373ca851c2db882c8

test:
  secret_key_base: 96ea9769b808dbdb9b7ab377bea2cd6a3d1f018331af28d68576afdb9f7728f6509794876761139391489e33dc5d1102a7db96d2280dc9cea307a73cfafd48ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
